03-Project-Source-Code/flixter/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

03-Project-Source-Code/flixter/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

03-Project-Source-Code/flixter/app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]
  skip_before_action :verify_authenticity_token

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)

    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

03-Project-Source-Code/flixter/app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]
  skip_before_action :verify_authenticity_token

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end

end

03-Project-Source-Code/flixter/app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

03-Project-Source-Code/flixter/app/helpers/courses_helper.rb
module CoursesHelper
end

03-Project-Source-Code/flixter/app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

03-Project-Source-Code/flixter/app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

03-Project-Source-Code/flixter/app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

03-Project-Source-Code/flixter/app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

03-Project-Source-Code/flixter/app/views/instructor/courses/show.html.erb
<script>
  $(function() {

    $('.new-lesson-button').click(function( event ) {
      var lessonURL=  $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonURL);
    });

  });

  $(function() {

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json', 
          data: { lesson: { row_order_position: ui.item.index() }}
        });
      }
    });

  });

  $(function() {

    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() }}
        });
      }
    });

  });
</script>

<br />
<div class="booyah-box col-10 offset-1">

  <h1 class="text-center"><%= current_course.title %></h1>
  <br />
  <%= image_tag current_course.image, class: "mx-auto d-block img-fluid" %>
  <br />

  <div class="text-center">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      Add a new section
    </button>
    <%= link_to 'View course as student', course_path(current_course), class: 'btn btn-warning float-right btn-lg' %>
  </div>

  <br class="clr" />

  <h4 class="text-center">Sections</h4>
  <br />

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url="<%= instructor_section_path(section) %>" class="section-li">

        <div class="header">
          <span class="fa fa-ellipsis-v"></span>
          <%= section.title %>
          <button type="button" class="btn btn-primary btn-sm float-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
            Add a new lesson
          </button>
        </div>

        <br class="clr"/>

        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path(lesson) %>">
              <div class="row">
                <div class="col-1">
                  <br />
                  <span class="fa fa-ellipsis-v"></span>
                </div>
                <div class="col-11 text-center">
                  <p>
                    <b><%= lesson.title %></b>
                  </p>
                  <p>
                    <%= lesson.subtitle %>
                  </p>
                </div>
              </div>
              <br class="clr"/>
            </li>
          <% end %>
        </ul>

      </li>
    <% end %>

  </ul>
</div>

<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newSectionModal">Add a New Section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a section", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#" , html: { id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add Lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>