03-Project-Source-Code/flixter/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

03-Project-Source-Code/flixter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

03-Project-Source-Code/flixter/app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    !free?
  end
end

03-Project-Source-Code/flixter/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

03-Project-Source-Code/flixter/app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last
    if lesson.blank? && section.previous_section
      return section.previous_section.lessons.rank(:row_order).last
    end
    return lesson
  end

end

03-Project-Source-Code/flixter/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

  def previous_section
    section = course.sections.where("row_order < ?", self.row_order).rank(:row_order).last
    return section
  end
  
end

03-Project-Source-Code/flixter/app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

03-Project-Source-Code/flixter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

03-Project-Source-Code/flixter/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

03-Project-Source-Code/flixter/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

03-Project-Source-Code/flixter/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premium Course',
        currency: 'usd'
      )
    end

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

03-Project-Source-Code/flixter/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrollment_for_current_lesson

  def show
  end

  private

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_enrollment_for_current_lesson
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: "You must be enrolled to view this lesson."
    end
  end

end

03-Project-Source-Code/flixter/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
  def privacy
  end
  
  def team
  end
end

03-Project-Source-Code/flixter/app/helpers/application_helper.rb
module ApplicationHelper
end

03-Project-Source-Code/flixter/app/helpers/courses_helper.rb
module CoursesHelper
end

03-Project-Source-Code/flixter/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

03-Project-Source-Code/flixter/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

03-Project-Source-Code/flixter/app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

03-Project-Source-Code/flixter/app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

03-Project-Source-Code/flixter/app/helpers/lessons_helper.rb
module LessonsHelper
end

03-Project-Source-Code/flixter/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

03-Project-Source-Code/flixter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/6.6.3/video-js.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

    <div id="flex-content-container">

      <!-- Navbar -->
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Flixter', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">

            <li class="nav-item">
              <%= link_to 'See all courses', courses_path, class: 'nav-link' %>
            </li>
            
            <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link' %>
              </li>

              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>

            <% else %>

              <li class="nav-item">
                <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
              </li>

              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
              </li>

            <% end %>
            
          </ul>
        </div>
      </nav>

      <% if notice.present? %>
        <p class="notice alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </div>
    
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3">
            <b>Teachers</b>
            <br />
            <%= link_to 'Teach a Course', new_instructor_course_path %>
            <br />
            <%= link_to 'My Dashboard', dashboard_path %>
            <br />
            <br />
          </div>
          <div class="col-12 col-sm-3">
            <b>About</b>
            <br />
            <%= link_to 'Team', team_path %>
            <br />
            <%= link_to 'Privacy Policy', privacy_path %>
            <br />
            <br />
          </div>
          <div class="col-12 col-sm-3">
            <b>Contact</b>
            <br />
            bhk1019@gmail.com
            <br />
            <br />
          </div>
          <div class="col-12 col-sm-3 social">
            <b>Social</b>
            <br />
            <%= link_to 'https://www.instagram.com/misterbenkim' do %>
              <span class="fa fa-instagram fa-2x social-button"></span>
            <% end %>
            <%= link_to 'http://github.com/bhk1019' do %>
              <span class="fa fa-github-square fa-2x social-button"></span>
            <% end %>
            <br />
            <br />
          </div>
        </div>
      </div>
    </div>

    <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

  </body>
</html>