03-Project-Source-Code/splurty/config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

03-Project-Source-Code/splurty/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

03-Project-Source-Code/splurty/app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3}
end

03-Project-Source-Code/splurty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

03-Project-Source-Code/splurty/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong>. The data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

end

03-Project-Source-Code/splurty/app/helpers/application_helper.rb
module ApplicationHelper
end

03-Project-Source-Code/splurty/app/helpers/quotes_helper.rb
module QuotesHelper
end

03-Project-Source-Code/splurty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            Steven
            <br />
            Universe
            <br />
            Quotes
          </div>
        <% end %>
      </div>

      <div class="col-4 hidden-sx-down slogan">
        All hail sucrose.
      </div>

      <div class="col-10 offset-1 offset-1 offset-sm-0 col-sm-5 links">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>

    </header>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute your quote.</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "What is the quote you want to add?", placeholder: "We are the Crystal Gems." %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Steven Universe" %>
              <br />
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            
          </div>
        </div>
      </div>
    </div>

    <hr />

    <br class="clear"/>

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class ="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "Give me another quote.", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Created by B.K., meep-morp connoisseur.
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

03-Project-Source-Code/splurty/app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About this site:</h1>

  <p>
    This is a Steven Universe quote generator created by Ben Kim. You can add your own favorite Steven Universe quotes by clicking on "Contribute".
  </p>

  <br />

  <p>The font used in the quotes is "Crewniverse", created by DeviantArt user <a href="http://maxigamer.deviantart.com">MaxiGamer</a>.</p>

  <br />

  <div class="row">
    <!-- <div class="col-12 col-sm-4">
      <%= image_tag 'ben.jpg', class: 'img-fluid' %>
    </div> -->

    <div class="col-12 col-sm-10">
      <!-- <h2 class="text-left">Ben Kim</h2> -->
      <br />
      <p>
        Ben is an educator, developer, and Steven Universe super fan.
      </p>
    </div>
  </div>
  <br class="clear">

  <br />
  <br />
  <br />
  <br />
  <br />



</div>

03-Project-Source-Code/splurty/app/views/quotes/index.html.erb
<h2>
  <span>Quote / No. <%= @quote.id %></span>
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />
<br />