03-Project-Source-Code/nomster/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
  	resources :comments, only: :create
  	resources :photos, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

03-Project-Source-Code/nomster/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

03-Project-Source-Code/nomster/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :place
	after_create :send_comment_email

	RATINGS = {
		'*': '1_star',
		'* *': '2_stars',
		'* * *': '3_stars',
		'* * * *': '4_stars',
		'* * * * *': '5_stars'
	}

	def humanized_rating
		RATINGS.invert[self.rating]
	end

	def send_comment_email
		NotificationMailer.comment_added(self).deliver_now
	end
end

03-Project-Source-Code/nomster/app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :picture, PictureUploader

	belongs_to :user
	belongs_to :place

end

03-Project-Source-Code/nomster/app/models/place.rb
class Place < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :photos
	
	geocoded_by :address
	after_validation :geocode
	validates :name, presence: true, length: { minimum: 3, too_short: "must be longer than %{count} characters." }
	validates :address, :description, presence: true
end

03-Project-Source-Code/nomster/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

03-Project-Source-Code/nomster/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

03-Project-Source-Code/nomster/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :rating)
	end
end

03-Project-Source-Code/nomster/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

	def create
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:picture, :caption)
	end
end

03-Project-Source-Code/nomster/app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@places = Place.order(:id).paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
				redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
			@place = Place.find(params[:id])
			@comment = Comment.new
			@photo = Photo.new
	end

	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render plain: 'Not Allowed', status: :forbidden
		end
	end

	def update
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render plain: 'Not Allowed', status: :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render plain: 'Not Allowed', status: :forbidden
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:name, :description, :address)
	end

end

03-Project-Source-Code/nomster/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

03-Project-Source-Code/nomster/app/helpers/application_helper.rb
module ApplicationHelper
end

03-Project-Source-Code/nomster/app/helpers/comments_helper.rb
module CommentsHelper
end

03-Project-Source-Code/nomster/app/helpers/photos_helper.rb
module PhotosHelper
end

03-Project-Source-Code/nomster/app/helpers/places_helper.rb
module PlacesHelper
end

03-Project-Source-Code/nomster/app/helpers/users_helper.rb
module UsersHelper
end

03-Project-Source-Code/nomster/app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
	<h1>Edit Your Place</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Update', class: 'btn btn-secondary' %>
	<% end %>
</div>

03-Project-Source-Code/nomster/app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
    	<%= image_tag 'slider1.JPG', class: 'd-block img-fluid' %>
    	<div class="carousel-caption d-none d-md-block">
    		<h3>Spacca Napoli</h3>
    	</div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.JPG', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
      	<h3>Roots Pizza</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.JPG', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
      	<h3>Favorite Chicago Restaurants</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<% @places.each do |place| %>
	<div class="booyah-box col-10 offset-1">
		<div class="row">
			<div class="col-12 col-md-9">
				<h1><%= link_to place.name, place_path(place) %></h1>
				<i><%= place.address %></i><br /><br />
				<p><%= place.description %></p>
				<% if place.user.present? %>
					<small>- <%= place.user.email %></small>
				<% end %>
				<br />
			</div>
			<div class="col-12 col-md-3">
				<% if place.photos.present? %>
					<div class="photos-index float-right">
						<%= image_tag place.photos.first.picture, class: 'index-image-size' %>
					</div>
				<% end %>
			</div>
		</div>

		<% if place.comments.present? %>
			<div class="col-12">
				<blockquote class="comment">
					<% if place.comments.last.humanized_rating.present? %>
						<b><%= place.comments.last.humanized_rating %></b> - <%= place.comments.last.message %>
					<% end %>
					<small>- <%= place.comments.last.user.email %></small>
				</blockquote>
			</div>
		<% end %>
	</div>
<% end %>

<dlv class="clear"></dlv>

<div class="col-10 offset-1">
	<%= will_paginate @places, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

03-Project-Source-Code/nomster/app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
	<h1>Add a Chicago Restaurant</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Create', class: 'btn btn-secondary' %>
	<% end %>
</div>

03-Project-Source-Code/nomster/app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
	<h1><%= @place.name %></h1>
	<i><%= @place.address %></i>
	<br /> <br />
	<p><%= @place.description %></p>

	<% if @place.latitude.present? && @place.longitude.present? %>
		<script>
		  function initMap() {
		    var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

		    var map = new google.maps.Map(document.getElementById('map'), {
		      zoom: 16,
		      center: myLatLng
		    });

		    var marker = new google.maps.Marker({
		      position: myLatLng,
		      map: map,
		      title: 'Hello World!'
		    });
		  }
		</script>

		<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGXlojgwzRzfG1l2Atn3qp_FISQ3-s9Ds&callback=initMap">
	    </script>

	  <div id="map"></div>

  <% end %>

  <br />


	<div class="float-right">
		<% if current_user && current_user == @place.user %>
			<%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-secondary' %>
			<%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
		<% end %>
	</div>

	<div class="float-right">
		<button type="button" class="btn btn-secondary float-right" data-toggle="modal" data-target="#photoModal">Add a photo</button>
	</div>

	<div class="float-right">
		<button type="button" class="btn btn-secondary float-right" data-toggle="modal" data-target="#myModal">Add a review</button>
	</div>

	<br /><br />
	<div class="clear"></div>
	<hr />

	<h2 class="float-left">Reviews</h2>
	<br class="clear">
	<div class="row col-10 offset-1">
		<% @place.comments.each do |comment| %>
			<div class="col-12 col-sm-6">
				<blockquote class="comment">
					<% if comment.humanized_rating.present? %>
						<b><%= comment.humanized_rating %></b> - <%= comment.message %>
					<% end %>
					<small>- <%= comment.user.email %></small>
				</blockquote>
			</div>
		<% end %>
	</div>
	<div class="clear"></div>
	<hr />

	<h2 class="float-left">Photos</h2>
	<br /><br class="clear">
	<div class="row col-10 offset-1">
		<% @place.photos.each do |photo| %>
			<div class="col-12 col-sm-6">
				<blockquote class="photo-display">
					<%= image_tag photo.picture, class: 'show-image-size' %>
					<p><% if photo.caption.present? %>
						<%= photo.caption %></p>
					<% end %>
				</blockquote>
			</div>
		<% end %>
	</div>


<div class="clear"></div>

<!-- Review Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for [@place, @comment] do |f| %>
	    	<div class="modal-body">
					<%= f.input :message, label: 'Review' %>
					<%= f.input :rating, as: :select, collection: Comment::RATINGS %>
	    	</div>
      	<div class="modal-footer">
    			<%= f.submit "Add a review", class: 'btn btn-secondary' %>
      	</div>
      <% end %>
    </div>
  </div>
</div>

<!-- Photo Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
      	<div class="modal-body">
					<%= f.input :picture %>
					<%= f.input :caption %>
      	</div>
      	<div class="modal-footer">
    			<%= f.submit "Add a photo", class: 'btn btn-secondary' %>
    		</div>
			<% end %>
    </div>
  </div>
</div>